apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reserveproxy
spec:
  selector:
    matchLabels:
      run: udagram-reserveproxy
  replicas: 2
  template:
    metadata:
      labels:
        run: udagram-reserveproxy
    spec:
      containers:
      - name: udagram-reserveproxy
        image: docker.io/hiennv00/udagram-reserveproxy:lasted
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m