apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
spec:
  selector:
    matchLabels:
      run: udagram-reverseproxy
  replicas: 1
  template:
    metadata:
      labels:
        run: udagram-reverseproxy
    spec:
      containers:
      - name: udagram-reverseproxy
        image: docker.io/hiennv00/udagram-reverseproxy:v2
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 500m
